[workspace]
resolver = "2"
members = [
    "crates/chunkforge-chunk",
    "crates/chunkforge-store",
]

[workspace.package]
edition = "2024"
license = "MIT"
rust-version = "1.85"
version = "0.1.0"

[workspace.dependencies]
blake3 = "1"
fastcdc = "5"
thiserror = "2"
tempfile = "3"
chunkforge-chunk = { path = "crates/chunkforge-chunk" }
