[workspace]
resolver = "2"
members = [
    "crates/chunkforge-chunk",
    "crates/chunkforge-index",
    "crates/chunkforge-store",
    "crates/chunkforge-remote",
    "crates/chunkforge-fuse",
    "crates/chunkforge-cli",
]

[workspace.package]
edition = "2024"
license = "MIT"
rust-version = "1.85"
version = "0.4.0"

[workspace.dependencies]
anyhow = "1"
blake3 = "1"
clap = { version = "4", features = ["derive"] }
fastcdc = "5"
thiserror = "2"
tempfile = "3"
chunkforge-chunk = { path = "crates/chunkforge-chunk" }
chunkforge-index = { path = "crates/chunkforge-index" }
chunkforge-store = { path = "crates/chunkforge-store" }
chunkforge-remote = { path = "crates/chunkforge-remote" }
chunkforge-fuse = { path = "crates/chunkforge-fuse" }
ureq = "3"
tiny_http = "0.12"
